name: Release plugin as zip file

on: 'release'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create zip file
        run: |
          zip -r woo-hide-original.zip .

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: woo-hide-original.zip


